# 外部API配置文件
# External API Configuration

external_api:
  # 基础连接配置
  base_url: "http://10.10.10.131:28001"
  sys_code: "SunAirProvince"
  
  # 认证配置（建议在生产环境使用环境变量）
  # 格式：${环境变量名:-默认值}
  username: "ScGuanLy"  # 可通过环境变量 EXTERNAL_API_USERNAME 覆盖
  password: "Suncere$0717"  # 可通过环境变量 EXTERNAL_API_PASSWORD 覆盖
  
  # API端点配置
  endpoints:
    token: "/api/airprovinceproduct/AirCityBaseCommon/GetExternalApiToken"
    summary_report: "/api/airprovinceproduct/dataanalysis/ReportDataQuery/GetReportForRangePagedListAsync"
    comparison_report: "/api/airprovinceproduct/dataanalysis/ReportDataQuery/GetReportForRangeCompareListAsync"
  
  # 性能配置
  timeout: 30  # 请求超时时间（秒）
  token_cache_time: 1800  # token缓存时间（秒），0.5小时 = 1800秒
  
  # 测试模式配置
  test_mode: false  # 设置为true时使用模拟数据，false时使用真实API
  mock_data_file: "external_api_mock_data.json"  # 模拟数据文件名（相对于config目录）

# 配置文件版本信息
version: "1.0.0"
last_updated: "2024-07-19"